// map between the Japanese names used in digimon-api and their English localization
const japaneseToEnglish: Record<string, string> = {
  "Aero V-dramon": "AeroVeedramon",
  "Agumon Hakase": "Agumon Expert",
  "Agumon (X-Antibody)": "Agumon X",
  Agnimon: "Agunimon",
  "Allomon (X-Antibody)": "Allomon X",
  "Ancient Beetmon": "AncientBeetlemon",
  "Ancient Garurumon": "AncientGarurumon",
  "Ancient Greymon": "AncientGreymon",
  "Ancient Irismon": "AncientKazemon",
  "Ancient Megatheriumon": "AncientMegatheriummon",
  "Ancient Mermaimon": "AncientMermaidmon",
  "Ancient Sphinxmon": "AncientSphinxmon",
  "Ancient Troiamon": "AncientTroiamon",
  "Ancient Volcamon": "AncientVolcanomon",
  "Ancient Wisemon": "AncientWisetmon",
  Andiramon: "Antylamon",
  "Andiramon (Deva)": "Antylamon (Deva)",
  Anubimon: "Anubismon",
  Hanumon: "Apemon",
  "Arkadimon Ultimate": "Arcadiamon",
  Algomon: "Argomon",
  "Algomon Ultimate": "Argomon Mega",
  Armadimon: "Armadillomon",
  Armagemon: "Armageddemon",
  "Mad Leomon: Armed Mode": "Armed MadLeomon",
  Assaultmon: "Armormon",
  "Arkadimon Perfect": "Arukadhimon",
  Archnemon: "Arukenimon",
  Alraumon: "Aruraumon",
  "Atlur Ballistamon": "AtlurBallistamon",
  Owlmon: "Aurumon",
  "Avenge Kidmon": "AvengeKidmon",
  "Dark Knightmon": "AxeKnightmon",
  "Deadly Axemon": "Axemon",
  Qinglongmon: "Azulongmon",
  "Balli Bastemon": "BalliBeastmon",
  "Bancho Golemon": "BanchoGolemon",
  "Bancho Leomon": "BanchoLeomon",
  "Bantyo Liomon": "BanchoLeomon",
  "Bancho Leomon Burst Mode": "BanchoLeomon Burst Mode",
  "Bantyo Liomon Burst Mode": "BanchoLeomon Burst Mode",
  "Bancho Lilimon": "BanchoLillymon",
  "Bancho Mamemon": "BanchoMamemon",
  "Bancho Stingmon": "BanchoStingmon",
  "Bao Huckmon": "BaoHackmon",
  Baromon: "Baronmon",
  Babydmon: "Bebydomon",
  Beelzebumon: "Beelzemon",
  "Beelzebumon (2010 Anime Version)": "Beelzemon (2010 Anime Version)",
  "Beelzebumon + Revolmon": "Beelzemon + Deputymon",
  "Beelzebumon + Starmons": "Beelzemon + Starmons",
  "Beelzebumon Blast Mode": "Beelzemon Blast Mode",
  "Beelzebumon X": "Beelzemon X",
  Blitzmon: "Beetlemon",
  "Beel Starrmon": "BelleStarmon",
  Beowolfmon: "Beowolfmon",
  Beowulfmon: "Beowolfmon",
  "Betamon (X-Antibody)": "Betamon X",
  "Big Mamemon": "BigMamemon",
  "Bio Darkdramon": "BioDarkdramon",
  "Bio Coatlmon": "BioQuetzalmon",
  "Bio Lotusmon": "BioRotosmon",
  "Bio Stegomon": "BioStegomon",
  "Bio Spinomon": "BioSupinomon",
  "Bio Thunderbirmon": "BioThunderbirdmon",
  "Bishop Chessmon (Black)": "BishopChessmon (Black)",
  "Bishop Chessmon (White)": "BishopChessmon (White)",
  Piyomon: "Biyomon",
  "Agumon (Black)": "BlackAgumon",
  "Black Agumon": "BlackAgumon",
  "Agumon (Black) (2006 Anime Version)": "BlackAgumon (2006 Anime Version)",
  "Black Agumon (2006 Anime Version)": "BlackAgumon (2006 Anime Version)",
  "XV-mon (Black)": "BlackExVeemon",
  "Gabumon (Black)": "BlackGabumon",
  "Black Gabumon": "BlackGabumon",
  "Black Galgomon": "BlackGargomon",
  "Garurumon (Black)": "BlackGarurumon",
  "Black Garurumon": "BlackGarurumon",
  "Black Tailmon": "BlackGatomon",
  "Greymon (Black)": "BlackGreymon",
  "Black Greymon": "BlackGreymon",
  "Black Growmon": "BlackGrowlmon",
  "Black Guilmon": "BlackGuilmon",
  "Black King Numemon": "BlackKingNumemon",
  "Black Saint Galgomon": "BlackMegaGargomon",
  "Metal Garurumon (Black)": "BlackMetalGarurumon",
  "Black Metal Garurumon": "BlackMetalGarurumon",
  "Black Rapidmon": "BlackRapidmon",
  "Black Seraphimon (DW3)": "BlackSeraphimon",
  "Black Shoutmon X7": "BlackShoutmon X7",
  "V-dramon (Black)": "BlackVeedramon",
  "Black War Greymon": "BlackWarGreymon",
  "Black War Greymon (X-Antibody)": "BlackWarGreymon X",
  "Black Megalo Growmon": "BlackWarGrowlmon",
  "Blade Kuwagamon": "BladeKuwagamon",
  Tinmon: "Blikmon",
  "Blue Meramon": "BlueMeramon",
  "Bomber Nanimon": "BomberNanimon",
  Blimpmon: "Brimpmon",
  Pucchiemon: "Bucchiemon",
  Puchiemon: "Bucchiemon",
  "Pucchiemon (Green)": "Bucchiemon (Green)",
  "Puchiemon (Green)": "Bucchiemon (Green)",
  Pukamon: "Bukamon",
  Valvemon: "Bulbmon",
  Burgamon: "Burgermon",
  "Burgamon Adult": "Burgermon Champion",
  Vritramon: "BurningGreymon",
  "Bushi Agumon": "BushiAgumon",
  Butterflymon: "Butterflymon",
  Butterflamon: "Butterflymon",
  Calmaramon: "Calmaramon",
  Calamaramon: "Calmaramon",
  Culumon: "Calumon",
  Candmon: "Candlemon",
  Cannonbeemon: "CannonBeemon",
  "Cannonbeemon (Aircraft Carrier)": "CannonBeemon (Aircraft Carrier)",
  "Captain Hookmon": "CaptainHookmon",
  "Catch Mamemon": "CatchMamemon",
  Centalmon: "Centarumon",
  Kentarumon: "Centarumon",
  "Cerberumon Jinrou Mode": "Cerberumon Werewolf Mode",
  "Cerberumon (X-Antibody)": "Cerberumon X",
  Chamelemon: "Chameleonmon",
  "Chaosdramon (X-Antibody)": "Chaosdramon X",
  "Chaos Dukemon": "ChaosGallantmon",
  "Chaos Dukemon Core": "ChaosGallantmon Core",
  "Chaos Grimmon": "ChaosGrimmon",
  "Chaos Seadramon": "ChaosMetalSeadramon",
  Chaosmon: "Chaosmon",
  Khaosmon: "Chaosmon",
  "Chaos Piemon": "ChaosPiedmon",
  "Chaos Greymon": "ChaosWarGreymon",
  Jyureimon: "Cherrymon",
  "Chibi Kamemon": "Chibitortomon",
  Chicomon: "Chibomon",
  "Cho·Hakkaimon": "Cho Hakkaimon",
  Chuumon: "Chuumon",
  Tyumon: "Chuumon",
  "N/A": "Citramon",
  "Clavis Angemon": "ClavisAngemon",
  "Clear Agumon": "ClearAgumon",
  Cocomon: "Conomon",
  Ganimon: "Crabmon",
  "Ganimon (X-Antibody)": "Crabmon X",
  "Yatagaramon (2006 Anime Version)": "Crowmon",
  "Lord Knightmon": "Crusadermon",
  ShouCutemon: "CuteShoutmon",
  Cyclomon: "Cyclonemon",
  Demon: "Daemon",
  "Demon Super Ultimate": "Daemon Super Mega",
  Darcmon: "Darcmon",
  "d'Arcmon": "Darcmon",
  "Dark Knightmon (Bagramon)": "Darkest AxeKnightmon",
  "Dark Knightmon (Blastmon)": "DarkKnightmon (Blastmon)",
  "Dark Knightmon (Duskmon)": "DarkKnightmon (Duskmon)",
  "Dark Knightmon (Gulfmon)": "DarkKnightmon (Gulfmon)",
  "Dark Knightmon (Lilithmon)": "DarkKnightmon (Lilithmon)",
  "Darkness Bagramon": "DarknessBagramon",
  "Dark Lizarmon": "Darkrizamon",
  "Dark Super Starmon": "DarkSuperStarmon",
  "Dark Tyranomon": "DarkTyrannomon",
  "Dark Volumon": "DarkVolumon",
  Pipimon: "Datirimon",
  "Death Airdramon": "DeathAirdramon",
  "Death Devimon": "DeathDevimon",
  "Death Metal Greymon": "DeathMetalGreymon",
  "Death Tyranomon": "DeathTyrannomon",
  "Decker Greymon": "DeckerGreymon",
  "Pico Devimon": "DemiDevimon",
  "Peti Meramon": "DemiMeramon",
  "Petit Meramon": "DemiMeramon",
  Chibimon: "DemiVeemon",
  Revolmon: "Deputymon",
  Delumon: "Deramon",
  Deramon: "Deramon",
  "Death-X-DORUgamon": "DexDORUgamon",
  "Death-X-DORUgoramon": "DexDORUgoramon",
  "Death-X-DORUguremon": "DexDoruGreymon",
  "Death-X-mon": "Dexmon",
  Diablomon: "Diaboromon",
  Dinobeemon: "DinoBeemon",
  Dinohumon: "Dinohyumon",
  Dinorexmon: "DinoRexmon",
  Dinotigermon: "DinoTigermon",
  Hangyomon: "Divermon",
  "Dobermon (X-Antibody)": "Dobermon X",
  Dogmon: "Doggymon",
  Rukamon: "Dolphmon",
  "Dorbickmon + Dragon Army": "Dorbickmon Darkness Mode One",
  "Dorbickmon Darkness Mode": "Dorbickmon Darkness Mode Two",
  DORUguremon: "Dorugreymon",
  "Dot Agumon": "DotAgumon",
  "Dot Falcomon": "DotFalcomon",
  "Dot Mirage Gaogamon": "DotMirageGaogamon",
  "Dot Shine Greymon": "DotShineGreymon",
  Dracmon: "Dracmon",
  Dracumon: "Dracmon",
  Dagomon: "Dragomon",
  "Dynasmon (X-Antibody)": "Dynasmon X",
  Crossmon: "Eaglemon",
  EBEmon: "Ebemon",
  "EBEmon (X-Antibody)": "Ebemon X",
  "Ebi Burgamon": "EbiBurgamon",
  Xuanwumon: "Ebonwumon",
  "El Doradimon": "ElDradimon",
  Elephamon: "Elephantmon",
  "Kaiser Greymon": "EmperorGreymon",
  "Majuu Lilithmon": "Evilbeast Laylamon",
  "Exo Grimmon": "ExoGrimmon",
  "Ex-Tyranomon": "ExTyrannomon",
  "XV-mon": "ExVeemon",
  "Nise Agumon Hakase": "Fake Agumon Expert",
  Funbeemon: "FanBeemon",
  Huanglongmon: "Fanglongmon",
  Phelesmon: "Feresmon",
  Fladramon: "Flamedramon",
  Flamon: "Flamemon",
  "Fla Wizarmon": "FlameWizardmon",
  "Flare Lizarmon": "Flarerizamon",
  Yukidarumon: "Frigimon",
  "Gattai Ancient Volcamon": "FusedAncientVolcanomon",
  "Gabumon (X-Antibody)": "Gabumon X",
  Gaioumon: "Gaiomon",
  Ragnamon: "Galacticmon",
  Dukemon: "Gallantmon",
  "Dukemon Crimson Mode": "Gallantmon Crimson Mode",
  "Dukemon (X-Antibody)": "Gallantmon X",
  Gerbemon: "Garbagemon",
  Galgomon: "Gargomon",
  Gargomon: "Gargoylemon",
  "Garudamon (X-Antibody)": "Garudamon X",
  "Garurumon X-Antibody": "Garurumon X",
  Tailmon: "Gatomon",
  "Tailmon (X-Antibody)": "Gatomon X",
  "Gazimon (X-Antibody)": "Gazimon X",
  "Geo Greymon": "GeoGreymon",
  "Gesomon (X-Antibody)": "Gesomon X",
  Deathmon: "Ghoulmon",
  "Deathmon (Black)": "Ghoulmon (Black)",
  "Giga Breakdramon": "GigaBreakdramon",
  "Giga Seadramon": "GigaSeadramon",
  "Giga Waru Monzaemon": "GigaWaruMonzaemon",
  Gizmon: "Gizumon",
  "Proto Gizmon": "Gizumon",
  "Gizmon: AT": "Gizumon AT",
  "Gizmon: XT": "Gizumon XT",
  "Gold Numemon": "GoldNumemon",
  Goddramon: "Goldramon",
  "Goddramon (X-Antibody)": "Goldramon X",
  "Gold V-dramon": "GoldVeedramon",
  "Golem Jiji Kamemon": "GolemJijiKamemon",
  "Gomamon (X-Antibody)": "Gomamon X",
  Gorimon: "Gorillamon",
  Gottsumon: "Gotsumon",
  "Gottsumon (X-Antibody)": "Gotsumon X",
  "Grand Generamon": "GrandGeneramon",
  "Grandis Kuwagamon": "GrandisKuwagamon",
  "Grandis Kuwagamon Honey Mode": "GrandisKuwagamon Honeybee Mode",
  "Gran Dracmon": "GranDracmon",
  "Grand Dracumon": "GranDracmon",
  "Gran Kuwagamon": "GranKuwagamon",
  "Grand Locomon": "GranLocomon",
  "Grappu Leomon": "GrapLeomon",
  "Grey Knightsmon": "GreyKnightsmon",
  "Greymon (X-Antibody)": "Greymon X",
  Gryzmon: "Grizzlymon",
  Growmon: "Growlmon",
  "Growmon (Orange)": "Growlmon (Orange)",
  "Growmon (X-Antibody)": "Growlmon X",
  Grottomon: "Grumblemon",
  Griffomon: "Gryphonmon",
  "Slash Angemon": "GuardiAngemon",
  "Guilmon (X-Antibody)": "Guilmon X",
  Gawappamon: "Gwappamon",
  "Hagurumon (X-Antibody)": "Hagurumon X",
  Holsmon: "Halsemon",
  "Herakle Kabuterimon": "HerculesKabuterimon",
  "Herakle Kabuterimon (X-Antibody)": "HerculesKabuterimon X",
  "Hi-Vision Monitamon": "Hi-VisionMonitamon",
  "Hi Andromon": "HiAndromon",
  "Hi Mugendramon": "HiMachineDramon",
  "Hisya Ryumon": "Hisyarumon",
  "Holy Digitamamon": "HolyDigitamamon",
  "Hustle Nanimon": "HustleNanimon",
  Hyougamon: "Hyogamon",
  "Ice Devimon": "IceDevimon",
  "Ice Devimon Enhancement Absorbent": "IceDevimon",
  "Ice Devimon Daipenmon Enhancement Absorbent":
    "IceDevimon-Daipenmon Enhancement",
  Panjyamon: "IceLeomon",
  "Panjyamon (X-Antibody)": "Panjyamon X",
  Indaramon: "Indramon",
  "Jungle Mojyamon": "J-Mojyamon",
  "Yaeger Dorulumon": "JagerDorulumon",
  "Kaiser Leomon": "JagerLoweemon",
  JESmon: "Jesmon",
  "Jet Mervamon": "JetMervamon",
  "Jet Silphymon": "JetSilphymon",
  Jewelbeemon: "JewelBeemon",
  "Jiji Shoutmon": "JijiShoutmon",
  "Jumbo Gamemon": "JumboGamemon",
  Kangalmon: "Kangarumon",
  Caprimon: "Kapurimon",
  Kapurimon: "Kapurimon",
  "Karatuki Numemon": "KaratsukiNumemon",
  "Karatsuki Numemon": "KaratsukiNumemon",
  Fairimon: "Kazemon",
  Garmmon: "KendoGarurumon",
  Sleipmon: "Kentaurosmon",
  "Cherubimon (Virtue)": "Kerpymon (Vaccine)",
  "Cherubimon (Vice)": "Kerpymon (Virus)",
  Chimairamon: "Kimeramon",
  Yggdrasill: "King Drasil",
  Yggdrasill_7D6: "King Drasil_7D6",
  "King Chessmon": "KingChessmon",
  "King Etemon": "KingEtemon",
  "Great King Scumon": "KingSukamon",
  "Knight Chessmon (Black)": "KnightChessmon (Black)",
  Kodokugumon: "KoDokugumon",
  Kougamon: "Kogamon",
  Kokabuterimon: "KoKabuterimon",
  Cockatrimon: "Kokatorimon",
  "Kokuwamon (X-Antibody)": "Kokuwamon X",
  Blizzarmon: "Korikakumon",
  Bearmon: "Kumamon",
  Chackmon: "Kumamon",
  Chrysalimon: "Kurisarimon",
  "Kuwagamon (X-Antibody)": "Kuwagamon X",
  Kyūkimon: "Kyukimon",
  Cupimon: "Kyupimon",
  "Lady Devimon": "LadyDevimon",
  "Gattai Lilithmon": "Laylamon Combined",
  "Leomon (X-Antibody)": "Leomon X",
  Duftmon: "Leopardmon",
  "Duftmon Leopard Mode": "Leopardmon Leopard Mode",
  "Duftmon (X-Antibody)": "Leopardmon X",
  Lilimon: "Lillymon",
  "Lilimon (X-Antibody)": "Lilymon X",
  "Loader Leomon": "LoaderLeomon",
  Wolfmon: "Lobomon",
  Lotusmon: "Lotosmon",
  Löwemon: "Loweemon",
  "Lucemon Falldown Mode": "Lucemon Chaos Mode",
  "Lucemon Satan Mode": "Lucemon Shadow Lord Mode",
  "Mach Gaogamon": "MachGaogamon",
  Mugendramon: "Machinedramon",
  "Mach Leomon": "MachLeomon",
  "Mad Leomon": "MadLeomon",
  "Mad Leomon (Final Mode)": "MadLeomon (Final Mode)",
  "Mad Leomon (Orochi Mode)": "MadLeomon (Orochimode)",
  "Holy Angemon": "MagnaAngemon",
  Holydramon: "Magnadramon",
  "Holydramon (X-Antibody)": "Magnadramon X",
  "Magna Garurumon": "MagnaGarurumon",
  "Magna Kidmon": "MagnaKidmon",
  "Magnamon (X-Antibody)": "Magnamon X",
  "Mail Birdramon": "MailBirdramon",
  "Belial Vamdemon": "MaloMyotismon",
  "Mamemon (X-Antibody)": "Mamemon X",
  Mametyramon: "MameTyramon",
  Mammon: "Mammothmon",
  "Mammon (X-Antibody)": "Mammothmon X",
  "Mantaraymon (X-Antibody)": "Mantaraymon X",
  "Marin Angemon": "MarineAngemon",
  "Marin Devimon": "MarineDevimon",
  "Master Tyranomon": "MasterTyrannomon",
  "Master V-dramon": "MasterVeedramon",
  Matadrmon: "Matadormon",
  "Medieval Dukemon": "MedievalDukemon",
  "Saint Galgomon": "MegaGargomon",
  "AtlurKabuterimon (Blue)": "MegaKabuterimon (Blue)",
  "Atlur Kabuterimon (Red)": "MegaKabuterimon (Red)",
  "Mega Seadramon": "MegaSeadramon",
  "Mega Seadramon (X-Antibody)": "MegaSeadramon X",
  "Megidramon (X-Antibody)": "Megidramon X",
  Meikuumon: "Meicoomon",
  Mechanorimon: "Mekanorimon",
  Mephismon: "Mephistomon",
  Mercuremon: "Mercurymon",
  Mercurymon: "Merukimon",
  "Metal Etemon": "MetalEtemon",
  "Metal Garurumon": "MetalGarurumon",
  "Metal Garurumon (X-Antibody)": "MetalGarurumon X",
  "Metal Greymon (2010 Anime Version)": "MetalGreymon (2010 Anime Version)",
  "Metal Greymon (Virus)": "MetalGreymon (Virus)",
  "Metal Greymon + Cyber Launcher": "MetalGreymon Cyberdramon",
  "Metal Greymon (X-Antibody)": "MetalGreymon X",
  Bolgmon: "MetalKabuterimon",
  "Metallife Kuwagamon": "MetallifeKuwagamon",
  "Metal Mamemon": "MetalMamemon",
  "Metal Mamemon (X-Antibody)": "MetalMamemon X",
  "Metal Fantomon": "MetalPhantomon",
  "Metal Phantomon": "MetalPhantomon",
  "Metal Piranimon": "MetalPiranimon",
  "Metal Tyranomon": "MetalTyrannomon",
  "Metal Tyranomon (X-Antibody)": "MetalTyrannomon X",
  Millenniumon: "Millenniummon",
  Minotaurmon: "Minotarumon",
  Minotarumon: "Minotarumon",
  "Minotaurmon Adult": "Minotarumon Champion",
  "Minotarumon Adult": "Minotarumon Champion",
  "Mirage Gaogamon": "MirageGaogamon",
  "Mirage Gaogamon Burst Mode": "MirageGaogamon Burst Mode",
  Mystimon: "Mistymon",
  "Modoki Betamon": "ModokiBetamon",
  "Monochromon (X-Antibody)": "Monochromon X",
  "Moon Millenniumon": "Moon=Millenniummon",
  "Mori Shellmon": "MoriShellmon",
  Mochimon: "Motimon",
  Motimon: "Motimon",
  Tsuchidarumon: "MudFrigimon",
  Murmuxmon: "Murmuxmon",
  Murmukusmon: "Murmuxmon",
  Murmusmon: "Murmuxmon",
  "Mush-Upped Mach Leomon": "Mush-Upped MachLeomon",
  Mushmon: "Mushroomon",
  "Muso Knightmon": "MusoKnightmon",
  Vamdemon: "Myotismon",
  Neamon: "Neemon",
  "Nefertimon (X-Antibody)": "Nefertimon X",
  "Nene Shademon": "NeneShademon",
  "Neo Crimson": "NeoCrimson",
  "Neo Devimon": "NeoDevimon",
  "Neo Vamdemon": "NeoMyotismon",
  "Neo Vamdemon Darkness Mode + Shoutmon":
    "NeoMyotismon Darkness Mode + Shoutmon",
  "Neo Vamdemon + Devimon + Lady Devimon": "NeoMyotismon Darkness Mode One",
  "Neo Vamdemon Darkness Mode": "NeoMyotismon Darkness Mode Two",
  Igamon: "Ninjamon",
  "Nise Drimogemon": "NiseDrimogemon",
  "Ochi Musyamon": "OchiMusyamon",
  Octmon: "Octomon",
  Orgemon: "Ogremon",
  Būmon: "Oinkmon",
  "Okuwamon (X-Antibody)": "Okuwamon X",
  "Omega Armamon BM": "OmegaArmamon BM",
  Omegamon: "Omnimon",
  "Omegamon (X-Antibody)": "Omnimon X",
  "Omegamon Zwart": "Omnimon Zwart",
  "Omega Shoutmon": "OmniShoutmon",
  Ofanimon: "Ophanimon",
  "Ofanimon Core": "Ophanimon Core",
  "Ofanimon Falldown Mode": "Ophanimon Falldown Mode",
  Opossummon: "Opossumon",
  Goatmon: "Oryxmon",
  "Otamamon (X-Antibody)": "Otamamon X",
  Ouryumon: "Owryumon",
  Bubbmon: "Pabumon",
  Pajramon: "Pajiramon",
  "Palmon (X-Antibody)": "Palmon X",
  "Pawn Chessmon (Black)": "PawnChessmon (Black)",
  "Pawn Chessmon (White)": "PawnChessmon (White)",
  "Pawn Shoutmon": "PawnShoutmon",
  Pegasmon: "Pegasusmon",
  Penmon: "Penguinmon",
  Bastemon: "Persiamon",
  "Petit Mamon": "PetitMamon",
  Phantomon: "Phantomon",
  Fantomon: "Phantomon",
  Hououmon: "Phoenixmon",
  Pidmon: "Piddomon",
  Piemon: "Piedmon",
  "Pile Volcamon": "PileVolcanomon",
  Pichimon: "Pitimon",
  Pitchmon: "Pitimon",
  Piccolomon: "Piximon",
  "Platinum Numemon": "PlatinumNumemon",
  "Platinum Scumon": "PlatinumSukamon",
  "Platiunum Sukamon": "PlatinumSukamon",
  "Platina Sukamon": "PlatinumSukamon",
  "Plesiomon (X-Antibody)": "Plesiomon X",
  "Prince Mamemon": "PrinceMamemon",
  "Prince Mamemon (X-Antibody)": "PrinceMamemon X",
  Pteranomon: "Pteramon",
  Pumpmon: "Pumpkinmon",
  "Punch Narabimon": "PunchNarabimon",
  Pinocchimon: "Puppetmon",
  Pinochimon: "Puppetmon",
  "Pteranimon X-Antibody": "Puteranomon X",
  Puttimon: "Puttimon",
  Puttomon: "Puttimon",
  "Queen Chessmon": "QueenChessmon",
  Coatlmon: "Quetzalmon",
  Bitmon: "Rabbitmon",
  Lighdramon: "Raidramon",
  "Rampage Greymon": "RampageGreymon",
  "Rapidmon Perfect": "Rapidmon Ultimate",
  "Raptor Sparrowmon": "RaptorSparrowmon",
  Ravmon: "Ravemon",
  "Ravmon Burst Mode": "Ravemon Burst Mode",
  Gokumon: "Reapermon",
  Baalmon: "Reapmon",
  "Red V-dramon": "RedVeedramon",
  "Red Vegimon": "RedVegiemon",
  Raptodramon: "Reptiledramon",
  "Reverse Weddinmon": "ReverseWeddinmon",
  Raihimon: "Rhihimon",
  "Rhino Kabuterimon": "RhinoKabuterimon",
  "Rhinomon (X-Antibody)": "Rhinomon X",
  Linkmon: "Rinkmon",
  "Rize Greymon": "RizeGreymon",
  Gokimon: "Roachmon",
  "Golemon (PS)": "Rockmon",
  "Rook Chessmon (Black)": "RookChessmon (Black)",
  "Rook Chessmon (White": "RookChessmon (White)",
  "Rosemon (X-Antibody)": "Rosemon X",
  "Rust Tyranomon": "RustTyranomon",
  "Deadly Tuwarmon": "Ruthless Tuwarmon",
  "Deadly Tuwarmon Hell Mode": "Ruthless Tuwarmon Beast Mode",
  Saberdramon: "Saberdramon",
  Sabirdramon: "Saberdramon",
  "Saber Leomon": "SaberLeomon",
  Sephirotmon: "Sakkakumon",
  "Sakuteki Monitamon": "SakutekiMonitamon",
  Salamandamon: "Salamandermon",
  Plotmon: "Salamon",
  "Plotmon (X-Antibody)": "Salamon X",
  "Sand Yanmamon": "SandYanmamon",
  "Santa Agumon": "SantaAgumon",
  Anomalocarimon: "Scorpiomon",
  "Anomalocarimon (X-Antibody)": "Scorpiomon X",
  "Scud Missimon": "ScudMissimon",
  "Seadramon (X-Antibody)": "Seadramon X",
  Shīsamon: "Seasarmon",
  Siesamon: "Seasarmon",
  Setmon: "Sethmon",
  "Black Seraphimon": "ShadowSeraphimon",
  "Toy Agumon (Black)": "ShadowToyAgumon",
  "Were Garurumon (Black)": "ShadowWereGarurumon",
  "Black Were Garurumon": "ShadowWereGarurumon",
  Shamamon: "Sharmamon",
  Shawujinmon: "Shawjamon",
  "Shima Unimon": "ShimaUnimon",
  "Shine Greymon Burst Mode": "ShineGreymon Burst Mode",
  "Shine Greymon Ruin Mode": "ShineGreymon Ruin Mode",
  "Tonosama Gekomon": "ShogunGekomon",
  Shonitamon: "Shounitamon",
  "Shoutmon + Jet Sparrow": "Shoutmon + Supersonic Sparrow",
  "Shoutmon X7 Superior Mode": "Shoutmon X7F Superior Mode",
  "Skull Baluchimon": "SkullBaluchimon",
  "Skull Greymon": "SkullGreymon",
  "Skull Knightmon": "SkullKnightmon",
  "Skull Knightmon: Big Axe Mode": "SkullKnightmon Mighty Axe Mode",
  "Skull Knightmon: Arrow Mode": "SkullKnightmon: Arrow Mode",
  "Skull Knightmon: Naginata Mode": "SkullKnightmon: Naginata Mode",
  "Skull Mammon": "SkullMammothmon",
  "Skull Mammon (X-Antibody)": "SkullMammothmon X",
  "Death Meramon": "SkullMeramon",
  "Skull Satamon": "SkullSatamon",
  Scorpiomon: "SkullScorpiomon",
  "Yuki Agumon": "SnowAgumon",
  "Yuki Agumon (2006 Anime Version)": "SnowAgumon (2006 Anime Version)",
  "Yukimi Botamon": "YukimiBotamon",
  "Snow Goburimon": "SnowGoburimon",
  "Snow Goblimon": "SnowGoburimon",
  Sorcerimon: "Sorcermon",
  Spadamon: "Spadamon",
  Supadamon: "Spadamon",
  "Starmon (X-Antibody)": "Starmon X",
  Scumon: "Sukamon",
  Sukamon: "Sukamon",
  "Super Starmon": "SuperStarmon",
  Superstarmon: "SuperStarmon",
  Shakomon: "Syakomon",
  Bakumon: "Tapirmon",
  Thunderbirmon: "Thunderbirdmon",
  Thunderballmon: "Thundermon",
  "Thunderballmon (X-Antibody)": "Thundermon X",
  "Tiger Vespamon": "TigerVespamon",
  Tobucatmon: "TobuCatmon",
  "Togemon (X-Antibody)": "Togemon X",
  "Tokomon (X-Antibody)": "Tokomon X",
  "Tonosama Mamemon": "TonosamaMamemon",
  "Torikara Ballmon": "TorikaraBallmon",
  Tortamon: "Tortomon",
  Tortomon: "Tortomon",
  Toucanmon: "Toucanmon",
  Tocanmon: "Toucanmon",
  "Toy Agumon": "ToyAgumon",
  "Triceramon (X-Antibody)": "Triceramon X",
  Tukaimon: "Tsukaimon",
  Tsunomon: "Tsunomon",
  Tunomon: "Tsunomon",
  "Tylomon (X-Antibody)": "Tylomon X",
  Tyranomon: "Tyrannomon",
  "Tyrant Kabuterimon": "TyrantKabuterimon",
  "Ulforce V-dramon": "UlforceVeedramon",
  "Ulforce V-dramon Future Mode": "UlforceVeedramon Future Mode",
  "Ulforce V-dramon (X-Antibody)": "UlforceVeedramon X",
  "Ultimate Brachiomon": "UltimateBrachiomon",
  "Ultimate Khaosmon": "UltimateKhaosmon",
  "Vademon (X-Antibody)": "Vademon X",
  Valdurmon: "Varodurumon",
  "V-dramon": "Veedramon",
  "V-mon": "Veemon",
  Vegimon: "Vegiemon",
  Velgrmon: "Velgemon",
  BEMmon: "Vemmon",
  "Venom Vamdemon": "VenomMyotismon",
  Vermillimon: "Vermilimon",
  "Elecmon (Violet)": "Vi-Elecmon",
  "Victory Greymon": "VictoryGreymon",
  Evilmon: "Vilemon",
  Volcamon: "Volcanomon",
  "War Greymon": "WarGreymon",
  "War Greymon (X-Antibody)": "WarGreymon X",
  "Megalo Growmon": "WarGrowlmon",
  "Megalo Growmon (X-Antibody)": "WarGrowlmon X",
  "Waru Monzaemon": "WaruMonzaemon",
  "Waru Seadramon": "WaruSeadramon",
  Zassoumon: "Weedmon",
  Wendimon: "Wendigomon",
  "Were Garurumon": "WereGarurumon",
  "Were Garurumon (X-Antibody)": "WereGarurumon X",
  "Whamon Perfect": "Whamon Ultimate",
  Wizarmon: "Wizardmon",
  Yasyamon: "Yaksamon",
  Yaksamon: "Yasyamon",
  Yatagaramon: "Yatakaramon",
  "Yotxu!Yotxu!mon": "Yo!Yo!mon",
  Pyocomon: "Yokomon",
  "Z'd Garurumon": "ZeedGarurumon",
  "Zeed Millenniummon": "ZeedMillenniummon",
  "Zeke Greymon": "ZekeGreymon",
  Shutumon: "Zephyrmon",
};

export const getEnglishName = (name: string) => {
  return japaneseToEnglish[name] || name;
};
